### PR TITLE
Update library to Maven and SC base/starter project

### PR DESCRIPTION
**Pull request by alexjhawk**
1/15

### CODE REVIEW

**Comment by alexjhawk** [comment]
This is PR 1 of 15 for the library migration to dual-Ant/Maven support. No explicit unit testing has been added, although support is included for it. Additionally, this PR will bring the library in line with https://github.com/hms-networks/sc-java-maven-starter-project, which will allow for a more consistent project format and structure.

**Comment by TomKimsey** [comment]
> This is PR 1 of 15 for the library migration to dual-Ant/Maven support. No explicit unit testing has been added, although support is included for it. Additionally, this PR will bring the library in line with https://github.com/hms-networks/sc-java-maven-starter-project, which will allow for a more consistent project format and structure.

Its probably a good time to come back to the idea of just having one solution center library repo. I think we are at the point where maintenance is a nightmare. For existing customers we can leave these repos up and document migration instructions in the new repo.

**Comment by it-hms** [comment]
@alexjhawk 
I think it makes sense to complete the sc-flexy library consolidation prior to adding maven support. Realistically there are some libraries that depend on 5-6 other libraries.

**Comment by alexjhawk** [comment]
> > This is PR 1 of 15 for the library migration to dual-Ant/Maven support. No explicit unit testing has been added, although support is included for it. Additionally, this PR will bring the library in line with https://github.com/hms-networks/sc-java-maven-starter-project, which will allow for a more consistent project format and structure.
> 
> Its probably a good time to come back to the idea of just having one solution center library repo. I think we are at the point where maintenance is a nightmare. For existing customers we can leave these repos up and document migration instructions in the new repo.

I agree that maintenance has become a nightmare. At this point, a conversation probably is warranted where we discuss the number of libraries and potentially combining some or all. 

With regards to this PR and the changes it provides, it will make library maintenance actually much simpler and easier. The new structure not only allows for us to add JUnit testing natively in the repo without additional work involved but will also handle dependencies in a much more intelligent/friendly manner. With the improved dependency handling, we will be able to code in an IDE and let Maven automatically manage the importing and loading of the library's dependencies onto the classpath. When we use multiple of these libraries in a project, Maven will handle the dependencies again such that one library won't be imported multiple times. 

Initially, I began the starter Maven project as a solution to the ongoing issues with automated building for these libraries but adapted it to be generic and applicable to any solution center project. With the intent of solving many testing and maintenance annoyances with the libraries and other projects, I would hope that this PR will actually help alleviate any nightmares we have now.

**Comment by alexjhawk** [comment]
This PR will be relocated to new, modern and combined library

**Pull request closed without merging**
